; PlatformIO Project Configuration File

;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting

; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:megaatmega2560]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino

; [env:uno]
; platform = atmelavr
; board = uno
; framework = arduino
; monitor_speed = 9600
; monitor_echo = yes
; monitor_eol = LF
; monitor_filters = send_on_enter
; build_flags = -DAPP_NAME=3
; build_src_filter = -<*> +<main.cpp> +<srvSerialStdio/> +<lab2-1App/> +<ddButton/> +<ddLed/>
; lib_deps =
;     Keypad
;     LiquidCrystal_I2C

; [env:uno-freertos]
; platform = atmelavr
; board = uno
; framework = arduino
; monitor_speed = 9600
; monitor_echo = yes
; monitor_eol = LF
; monitor_filters = send_on_enter
; build_flags = -DAPP_NAME=4
; build_src_filter = -<*> +<main.cpp> +<srvSerialStdio/> +<lab2-2App/> +<ddButton/> +<ddLed/>
; lib_deps =
;     Keypad
;     LiquidCrystal_I2C
;     feilipu/FreeRTOS

; [env:mega-freertos-3-1]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_echo = yes
; monitor_eol = LF
; monitor_filters = send_on_enter
; build_flags = -DAPP_NAME=5
; build_src_filter = -<*> +<main.cpp> +<srvSerialStdio/> +<lab3-1App/> +<ddLed/>
; lib_deps =
;     LiquidCrystal_I2C
;     feilipu/FreeRTOS@^11.1.0-3

; [env:mega-freertos-3-2]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_echo = yes
; monitor_eol = LF
; monitor_filters = send_on_enter
; build_flags = -DAPP_NAME=6
; build_src_filter = -<*> +<main.cpp> +<srvSerialStdio/> +<lab3-2App/> +<ddLed/>
; lib_deps =
;     LiquidCrystal_I2C
;     feilipu/FreeRTOS@^11.1.0-3

; [env:mega-freertos-4-1]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_echo = yes
; monitor_eol = LF
; monitor_filters = send_on_enter
; build_flags = -DAPP_NAME=7
; build_src_filter = -<*> +<main.cpp> +<srvSerialStdio/> +<lab4-1App/> +<ddRelay/>
; lib_deps =
;     LiquidCrystal_I2C
;     feilipu/FreeRTOS@^11.1.0-3

; [env:mega-freertos-4-2]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_echo = yes
; monitor_eol = LF
; monitor_filters = send_on_enter
; build_flags = -DAPP_NAME=8
; build_src_filter = -<*> +<main.cpp> +<srvSerialStdio/> +<lab4-2App/> +<ddKeypad/> +<ddLcd/> +<ddRelay/> +<ddServo/>
; lib_deps =
;     LiquidCrystal_I2C
;     feilipu/FreeRTOS@^11.1.0-3
;     Keypad
;     Servo

[env:mega-freertos-5-1]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
monitor_echo = yes
monitor_eol = LF
monitor_filters = send_on_enter
build_flags = -DAPP_NAME=9
build_src_filter = -<*> +<main.cpp> +<srvSerialStdio/> +<lab5-1App/> +<ddTempSensor/> +<ddPotentiometer/> +<ddRelay/> +<ddLed/> +<ddMotorDriver/>
lib_deps =
    feilipu/FreeRTOS@^11.1.0-3
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    LiquidCrystal_I2C
    Keypad
    Servo

[env:mega-freertos-5-2]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
monitor_echo = yes
monitor_eol = LF
monitor_filters = send_on_enter
build_flags = -DAPP_NAME=10
build_src_filter = -<*> +<main.cpp> +<srvSerialStdio/> +<lab5-2App/> +<ddTempSensor/> +<ddPotentiometer/> +<ddRelay/> +<ddLed/> +<ddMotorDriver/>
lib_deps =
    feilipu/FreeRTOS@^11.1.0-3
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    LiquidCrystal_I2C
